### ISSUE TITLE
Reproの送信するイベント名の変更

### ISSUE THREAD

**Issue by interfacebuilder** [monolink-corp/management#6]
# What

- Reproで送信するイベント名を変更する。
 - 特に会員登録部分。
 - Android 側も同時に修正する

# Why 

- 旧来のReproイベント送信時にパラメータも辞書型で送りつけていたが、管理画面側では意味の無いデータとして処理されていることが判明。
- パラメータで異なるイベントとしての集計が出来ない為、イベント名を替えることになった。
 - 例：会員登録→mailとfacebookの新規登録を今まで はパラメータにしていたが、regist_email, regist_facebook といった具合にイベント名で違うものとして送る。

# Do

- 実際のイベント名についてはコメント欄にて追記していく

**Comment by interfacebuilder** [comment]
### Android向けトラックイベント実装方針

- 基本はiOSの移植になる。
- MLViewCotnrollerのtrackメソッドで、ReproとGoogleAnalyticsによる送信（それぞれReproHelper、AnalyticsHelperクラスでイベント送信をしている）、AdjustHelper にも個別にイベント送信をしているので移植していく。

**Comment by igreenwood** [comment]
@interfacebuilder  `ReproTrack:  make_append_part_1995` みたいな感じでIDをつけると、一瞬でコンソールの上限の200件を超えると思うので、ID系は送るの諦めるしかないかなという気がするのですがどうでしょう？ 🤔

**Comment by igreenwood** [comment]
AndroidはlabelでuserIdなど送っている部分は、送らないように変更しました

**Comment by igreenwood** [comment]
labelを使っていそうなのは、
```
MLSampleDetailViewController、MakeCompletedViewController、MLTopTabBarController、URLRoutes
```
あたりですかね。（１ファイルに複数使用箇所がある可能性もあります）
